# Excerpted from issue #918

Login:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/addons/project/lib/Login.php'

User:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/addons/project/lib/User.php'

Contact:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/addons/project/lib/Contact.php'