# .github/labeler.yml 
# components:
#   - changed-files:
#       - any-glob-to-any-file: src/components/*
docs:
- all:
  - changed-files:
    - any-glob-to-any-file: ['docs/**', 'README.md', 'AUTHORS.rst', 'CITATION.cff']
    - all-globs-to-any-file: '!docs/source/news/*'
